language: go
before_install:
  - go get -u github.com/golang/dep/cmd/dep
install:
  - dep ensure
script: 
  - go test ./...
  - go build main.go
  - go build cmd/util/transformConfig.go
  - go build cmd/migration/isso/main.go
notifications:
  email: false